name: build_and_push_libs
on: [push]
jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: khjtony/sensor-hub-buildtools:latest
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
      - uses: addnab/docker-run-action@v3
        with:
          image: khjtony/sensor-hub-buildtools:latest
          run: PUSH_BINARY=yes /workspace/build_all.sh
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            docker run khjtony/sensor-hub-buildtools:latest
